/*$file${.::Washingmachine_Qpn.ino} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: Washingmachine_Qpn.qm
* File:  ${.::Washingmachine_Qpn.ino}
*
* This code has been generated by QM 5.2.1 <www.state-machine.com/qm>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* SPDX-License-Identifier: GPL-3.0-or-later
*
* This generated code is open source software: you can redistribute it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation.
*
* This code is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
* more details.
*
* NOTE:
* Alternatively, this generated code may be distributed under the terms
* of Quantum Leaps commercial licenses, which expressly supersede the GNU
* General Public License and are specifically designed for licensees
* interested in retaining the proprietary status of their code.
*
* Contact information:
* <www.state-machine.com/licensing>
* <info@state-machine.com>
*/
/*$endhead${.::Washingmachine_Qpn.ino} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpn.h"     // QP-nano framework for Arduino

#include "Arduino.h"  // Main include file for the Arduino SDK

//============================================================================
// declare all AO classes...
/*$declare${AOs::Washingmachine} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Washingmachine} ...................................................*/
typedef struct Washingmachine {
/* protected: */
    QActive super;

/* public: */
    uint8_t counter_;
    bool isLedOn_;
} Washingmachine;

/* public: */
static void Washingmachine_blink(Washingmachine * const me);
extern const uint8_t Washingmachine_washingLength_;
extern const uint8_t Washingmachine_rinsingLength_;
extern const uint8_t Washingmachine_spinningLength_;

/* protected: */
static QState Washingmachine_initial(Washingmachine * const me);
static QState Washingmachine_Loading(Washingmachine * const me);
static QState Washingmachine_Running(Washingmachine * const me);
static QState Washingmachine_Washing(Washingmachine * const me);
static QState Washingmachine_Rinsing(Washingmachine * const me);
static QState Washingmachine_Spinning(Washingmachine * const me);
/*$enddecl${AOs::Washingmachine} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
//...

// AO instances and event queue buffers for them...
Washingmachine AO_Washingmachine;
static QEvt l_washingmachineQSto[10]; // Event queue storage for Washingmachine
//...

//============================================================================
// QF_active[] array defines all active object control blocks ----------------
QActiveCB const Q_ROM QF_active[] = {
    { (QActive *)0,           (QEvt *)0,        0U                  },
    { (QActive *)&AO_Washingmachine,  l_washingmachineQSto,     Q_DIM(l_washingmachineQSto) }
};

//============================================================================
// various constants for the application...
enum {
    BSP_TICKS_PER_SEC = 100, // number of system clock ticks in one second
    LED_L = 13               // the pin number of the on-board LED (L)
};

//............................................................................
void setup() {
    // initialize the QF-nano framework
    QF_init(Q_DIM(QF_active));

    // initialize all AOs...
    QActive_ctor(&AO_Washingmachine.super, Q_STATE_CAST(&Washingmachine_initial));

    // initialize the hardware used in this sketch...
    pinMode(LED_L, OUTPUT); // set the LED-L pin to output
}

//............................................................................
void loop() {
    QF_run(); // run the QF-nano framework
}

//============================================================================
// interrupts...
ISR(TIMER2_COMPA_vect) {
    QF_tickXISR(0); // process time events for tick rate 0
}

//============================================================================
// QF callbacks...
void QF_onStartup(void) {
    // set Timer2 in CTC mode, 1/1024 prescaler, start the timer ticking...
    TCCR2A = (1U << WGM21) | (0U << WGM20);
    TCCR2B = (1U << CS22 ) | (1U << CS21) | (1U << CS20); // 1/2^10
    ASSR  &= ~(1U << AS2);
    TIMSK2 = (1U << OCIE2A); // enable TIMER2 compare Interrupt
    TCNT2  = 0U;

    // set the output-compare register based on the desired tick frequency
    OCR2A  = (F_CPU / BSP_TICKS_PER_SEC / 1024U) - 1U;
}
//............................................................................
void QV_onIdle(void) {   // called with interrupts DISABLED
    // Put the CPU and peripherals to the low-power mode. You might
    // need to customize the clock management for your application,
    // see the datasheet for your particular AVR MCU.
    SMCR = (0 << SM0) | (1 << SE); // idle mode, adjust to your project
    QV_CPU_SLEEP();  // atomically go to sleep and enable interrupts
}
//............................................................................
Q_NORETURN Q_onAssert(char const Q_ROM * const module, int location) {
    // implement the error-handling policy for your application!!!
    (void)module;
    (void)location;
    QF_INT_DISABLE(); // disable all interrupts
    QF_RESET();  // reset the CPU
    for (;;) {
    }
}

//============================================================================
// define all AO classes (state machine)...
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 690U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpn version 6.9.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/

/*$define${AOs::Washingmachine} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

/*${AOs::Washingmachine} ...................................................*/
const uint8_t Washingmachine_washingLength_ = 50;

const uint8_t Washingmachine_rinsingLength_ = 30;

const uint8_t Washingmachine_spinningLength_ = 40;


/*${AOs::Washingmachine::blink} ............................................*/
static void Washingmachine_blink(Washingmachine * const me) {
    if (me->isLedOn_) {
      digitalWrite(LED_L, HIGH);
    }
    else {
      digitalWrite(LED_L, LOW);
    }

    me->isLedOn_ = !me->isLedOn_;
}

/*${AOs::Washingmachine::SM} ...............................................*/
static QState Washingmachine_initial(Washingmachine * const me) {
    /*${AOs::Washingmachine::SM::initial} */
    QActive_armX((QActive *)me, 0U, BSP_TICKS_PER_SEC/8U, BSP_TICKS_PER_SEC/8U);
    Serial.begin(9600);
    pinMode(LED_BUILTIN, OUTPUT);
    return Q_TRAN(&Washingmachine_Loading);
}

/*${AOs::Washingmachine::SM::Loading} ......................................*/
static QState Washingmachine_Loading(Washingmachine * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Washingmachine::SM::Loading} */
        case Q_ENTRY_SIG: {
            digitalWrite(LED_L, LOW);
            Serial.println(F("Loading"));
            Serial.println(F("  Door open."));
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Washingmachine::SM::Loading} */
        case Q_EXIT_SIG: {
            Serial.println(F("  Door closed."));
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Washingmachine::SM::Loading::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Washingmachine_Running);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Washingmachine::SM::Running} ......................................*/
static QState Washingmachine_Running(Washingmachine * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Washingmachine::SM::Running} */
        case Q_ENTRY_SIG: {
            Serial.println(F("Running"));
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Washingmachine::SM::Running::initial} */
        case Q_INIT_SIG: {
            status_ = Q_TRAN(&Washingmachine_Washing);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}

/*${AOs::Washingmachine::SM::Running::Washing} .............................*/
static QState Washingmachine_Washing(Washingmachine * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Washingmachine::SM::Running::Washing} */
        case Q_ENTRY_SIG: {
            me->counter_ = 0;
            Serial.println(F("  Washing"));
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Washingmachine::SM::Running::Washing::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            me->counter_++;
            /*${AOs::Washingmachine::SM::Running::Washing::Q_TIMEOUT::[finished]} */
            if (me->counter_ > Washingmachine_washingLength_) {
                status_ = Q_TRAN(&Washingmachine_Rinsing);
            }
            /*${AOs::Washingmachine::SM::Running::Washing::Q_TIMEOUT::[else]} */
            else {
                if (me->counter_ % 4 == 0) {
                  Washingmachine_blink(me);
                }
                status_ = Q_HANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Washingmachine_Running);
            break;
        }
    }
    return status_;
}

/*${AOs::Washingmachine::SM::Running::Rinsing} .............................*/
static QState Washingmachine_Rinsing(Washingmachine * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Washingmachine::SM::Running::Rinsing} */
        case Q_ENTRY_SIG: {
            me->counter_ = 0;
            Serial.println(F("  Rinsing"));
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Washingmachine::SM::Running::Rinsing::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            me->counter_++;
            /*${AOs::Washingmachine::SM::Running::Rinsing::Q_TIMEOUT::[finished]} */
            if (me->counter_ > Washingmachine_rinsingLength_) {
                status_ = Q_TRAN(&Washingmachine_Spinning);
            }
            /*${AOs::Washingmachine::SM::Running::Rinsing::Q_TIMEOUT::[else]} */
            else {
                if (me->counter_ % 2 == 0) {
                  Washingmachine_blink(me);
                }
                status_ = Q_HANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Washingmachine_Running);
            break;
        }
    }
    return status_;
}

/*${AOs::Washingmachine::SM::Running::Spinning} ............................*/
static QState Washingmachine_Spinning(Washingmachine * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Washingmachine::SM::Running::Spinning} */
        case Q_ENTRY_SIG: {
            me->counter_ = 0;
            Serial.println(F("  Spinning"));
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Washingmachine::SM::Running::Spinning::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            me->counter_++;
            /*${AOs::Washingmachine::SM::Running::Spinning::Q_TIMEOUT::[finished]} */
            if (me->counter_ > Washingmachine_spinningLength_) {
                status_ = Q_TRAN(&Washingmachine_Loading);
            }
            /*${AOs::Washingmachine::SM::Running::Spinning::Q_TIMEOUT::[else]} */
            else {
                Washingmachine_blink(me);
                status_ = Q_HANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Washingmachine_Running);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Washingmachine} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
//...

